add_newline = false

[aws]
# format = '[$symbol$profile(\($region\))]($style) '
style = "bold yellow"
symbol = " "

[aws.region_aliases]
us-east-1 = "va"
us-east-2 = "oh"
us-west-1 = "ca"
us-west-2 = "or"

[cmd_duration]
min_time = 2_000
style = "bold blue"
show_notifications = true

[custom.nomad]
command = """
if [[ $NOMAD_ADDR =~ ".*.prod..*" ]]; then
    echo "Prod"
elif [[ $NOMAD_ADDR =~ ".*.staging..*" ]]; then
    echo "Staging"
elif [[ $NOMAD_ADDR =~ "http://192.*" ]]; then
    echo "Vagrant"
elif [[ $NOMAD_ADDR =~ "http://127.*" ]]; then
    echo "Local"
fi
"""
when = """ [[ -v NOMAD_TOKEN ]] && [[ -v NOMAD_ADDR ]] """
format = "$symbol [$output]($style) "
symbol = ""
shell = ["sh"]

[directory]
truncation_symbol = "…/"
truncation_lenth = 5
style = "bold blue"

[gcloud]
disabled = true

[git_status]
conflicted = " "
ahead = " ${count}"
behind = " ${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = ""
stashed = '[ \($count\)](yellow) '
modified = "[ ](blue)"
staged = '[ \($count\)](green) '
renamed = "➜"
deleted = " "

[terraform]
disabled = true
